name: Run Bioinformatics Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Environment
        run: |
          sudo apt-get install -y r-base perl default-jdk
      - name: Run Automation
        run: bash run_automation.sh
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: project-output
          path: results.csv

